kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-hacker-rb2
  namespace: my-cicd
subjects:
  - kind: ServiceAccount
    name: sa-hacker
    namespace: my-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
